version: 0.2

phases:
  install:
    commands: 
      - npm install -g hexo-cli
      - npm install
      - apt-get update
      - apt-get install -y awscli
    runtime-versions:
      nodejs: 10

  build: 
    commands:
      - hexo generate
  artifacts:
    files:
      - '**/*'

  post_build: 
    commands:
      - cd public/ && aws s3 sync . s3://stark-international-inc-2019/